### ISSUE TITLE
[Bug] Anime iFrame causes page to jump

### ISSUE THREAD

**Issue by 100chilly** [100chilly/100chilly.github.io#1]
When your load [100chilly.online](https://www.100chilly.online/), the Anime/Anime iFrame section causes the page to jump to the iFrame instead of beginning at the top of the page.
Image explaining what I am talking about.
![Image of the issue](http://i.imgur.com/0h1IXDI.gif)
I would like some help in identifying and implanting a fix.

**Comment by ThatSava** [comment]
Can you try disabling js and seeing if this still happens?

**Comment by 100chilly** [comment]
@andrejsavikin are you saying disable the iFrame's JavaScript or the website JavaScript itself?

**Comment by ThatSava** [comment]
Disable all js in your browser, just for testing

**Comment by ThatSava** [comment]
@100chilly After a bit investigation, the issue is caused by a javascript script within the framed website. Not sure how to resolve it though

**Comment by 100chilly** [comment]
I had a feeling it was the iFrame itself. I'll see if I can find a better alternative. Thanks @andrejsavikin!

**Comment by 100chilly** [comment]
Closed due to ending up replacing iFrame with a clickable image.
